### ISSUE TITLE
Freeze on button pressed in glTFLoadAssetFromFilename

### ISSUE THREAD

**Issue by Shevchenko-Alexander** [rdeioris/glTFRuntimeOBJ#2]
Hello!

When I try to load a mesh on button pressed it freezes in glTFRuntimeOBJFunctionLibrary.cpp (line 577)

![image](https://github.com/rdeioris/glTFRuntimeOBJ/assets/5353910/ca2d3fac-e2f1-4897-890b-7099b656267b)

![image](https://github.com/rdeioris/glTFRuntimeOBJ/assets/5353910/c439aa11-316b-4482-abb5-969b5186d21d)

Am I doing something wrong? It happens also if I use the async load mesh version
Thank you in advance!

**Comment by rdeioris** [comment]
Hi, can you share the asset?

**Comment by Shevchenko-Alexander** [comment]
Thank you for your fast reply, sure, here is the asset
[Mesh.zip](https://github.com/user-attachments/files/15801368/Mesh.zip)

**Comment by rdeioris** [comment]
@Shevchenko-Alexander fixed in latest master (the problem existed only in non-async mode)

**Comment by Shevchenko-Alexander** [comment]
@rdeioris that was fast, thank you!
